### ISSUE TITLE
Workshop with Cloud Architect.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-experiment#10]
The 3 and 4 des. 2018. A cloud architect will visit me at my office to discuss the architecture of the first prof of concept.

**Comment by pazdedav** [comment]
Great sessions and discussions, thanks for that @gjersvik . As we agreed, I started with making diagrams to capture key ideas and areas. I will add it to `designdocs` folder.

**Comment by gjersvik** [comment]
Yes was a very useful workshop thanks @pazdedav
