### ISSUE TITLE
Cleanup and consolidate design docs.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-experiment#16]
We have the nice design doc written by @pazdedav. We have some in the wiki. And soon we may have a webpage or other sources.

Need to just get ahead of it before it becomes to fragmented.

**Comment by pazdedav** [comment]
@gjersvik: If you plan to use **GitHub Pages**, we could have all the docs in markdown and let GitHub Pages generate html++ from it (quite popular option). Another option is to move `designdocs` to Wiki (this however gives limited branding & design capabilities.

**Comment by gjersvik** [comment]
Closing issue before archiving.
