### ISSUE TITLE
Prof of concept Gateway service.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-experiment#5]
Find and setup the best candidate for the full solution.

- [x] Evaluate Apache Guacamole.
- [x] Apache Guacamole running in azure.
- [ ] Install Guacamole with script
- [ ] Set new admin user and password and part of script.
- [ ] Pack deployment into template using extension.
- [ ] Record demo.

**Comment by pazdedav** [comment]
One potential candidate for evaluation could be [Apache Guacamole](https://guacamole.apache.org/).

**Comment by gjersvik** [comment]
After reading the doc of Apache Guacamole it seems like a nice fit for sepes but have some issues:

1. Do not support disable of clipboard. There is an issue on the topic: https://issues.apache.org/jira/browse/GUACAMOLE-381 We may have to contribute a fix to this issue.
2. It seems how the connections are handled in a very static way. It may require extra code to handle a more dynamic connections without making it open.

**Comment by gjersvik** [comment]
Was able to get it to run in azure on Thursday. Its sadly what i like to call Linux hard. Not a simple install more of good luck hope your distro have some good maintainers install. Was able to find a install script that finally worked. https://github.com/MysticRyuujin/guac-install And was able to get guacamole installed on a linux host talking to a windows box on the same network without public ip.

I think we have something here but its not a turn key solutions in any way.

**Comment by gjersvik** [comment]
I think the easiest way to get something simple working. Is to just run the install script as part of cloud-init. And wrap the whole ting into a template or script of some kind.

**Comment by pazdedav** [comment]
We should have a discussion about how we are going to provision all resources for "Shared Services" components, as well as for pods (excluding what a vendor will provision). To be able to automate everything we need to:

- use Resource Manager templates with parameter files - it will define our infrastructure
- use VM Extension to complete any in-guest configuration & installation

Should we have a quick chat about it, @gjersvik ?

**Comment by gjersvik** [comment]
@pazdedav sure we can have a chat my idea was to use Resource Manager templates with cloud init. As i have worked with cloud init in the past.

**Comment by gjersvik** [comment]
Stopped working on this task. Have done the tests i need to test this tech out an know its strength and weaknesses. Me and @fmell have designed a demo of a pod where the gateway is not needed. (yet) I want to focus my time on a demo proving vnet <-> storage account security.

**Comment by gjersvik** [comment]
Closing issue before archiving.
