### ISSUE TITLE
Azure access control

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-experiment#6]
See if Azure access control can give the perquisite granularity for this project. Or if we need to create a new control panel for creation of new resources.
Also look at automatically generation of access as new networks are brought up. New roles or something similar?

**Comment by pazdedav** [comment]
Azure RBAC gives a high granularity of permissions defined for each __resource__ on the Resource Provider API operation level. If none of built-in roles fits your purpose, you can easily create [custom roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles) with a desired scope of permissions.

**Comment by gjersvik** [comment]
Very limited access to Azure AD makes this one difficult. Will have to look into of whats there is enough or if we need to create a custom control panel app.

**Comment by gjersvik** [comment]
Closing issue before archiving.
